### ISSUE TITLE
why is jquery included

### ISSUE THREAD

**Issue by iongion** [9elements/academy-webdev-bootstrap#6]
I have noticed this in the config:
```
'jquery': path.resolve(sourceFiles + '/javascripts/vendor/jquery-1.11.3-min.js')
```

Is it really needed to be there or is just provided as a sample ?
If it is a sample, you could comment it out and add some documentation on top

**Comment by sebastiandeutsch** [comment]
Good observation. I removed it since it should be imported via npm.
